// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoAcoesSustentaveis.Infrastructure.Data.AppContext;

#nullable disable

namespace Projeto_SCFII.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjetoAcoesSustentaveis.Infrastructure.Domain.Entities.Cargo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NomeCargo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Cargos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NomeCargo = "Desenvolvedor"
                        });
                });

            modelBuilder.Entity("ProjetoAcoesSustentaveis.Infrastructure.Domain.Entities.Departamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NomeDepartamento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Departamentos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NomeDepartamento = "Departamento de TI"
                        });
                });

            modelBuilder.Entity("ProjetoAcoesSustentaveis.Infrastructure.Domain.Entities.Endereco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CEP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Complemento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logradouro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<string>("PontoReferencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Enderecos");
                });

            modelBuilder.Entity("ProjetoAcoesSustentaveis.Infrastructure.Domain.Entities.Genero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("NomeGenero")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Generos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Homem cisgênero",
                            NomeGenero = "Masculino"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Mulher cisgênero",
                            NomeGenero = "Feminino"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Pessoa que não se identifica dentro do binário homem/mulher",
                            NomeGenero = "Não binário"
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "Pessoa trans identificada como homem",
                            NomeGenero = "Transgênero Homem"
                        },
                        new
                        {
                            Id = 5,
                            Descricao = "Pessoa trans identificada como mulher",
                            NomeGenero = "Transgênero Mulher"
                        },
                        new
                        {
                            Id = 6,
                            Descricao = "Pessoa cuja identidade de gênero varia com o tempo",
                            NomeGenero = "Gênero Fluído"
                        },
                        new
                        {
                            Id = 7,
                            Descricao = "Pessoa sem identidade de gênero definida",
                            NomeGenero = "Agênero"
                        },
                        new
                        {
                            Id = 8,
                            Descricao = "Pessoa com características sexuais diversas",
                            NomeGenero = "Intersexo"
                        },
                        new
                        {
                            Id = 9,
                            Descricao = "Pessoa que opta por não declarar o gênero",
                            NomeGenero = "Prefere não dizer"
                        });
                });

            modelBuilder.Entity("ProjetoAcoesSustentaveis.Infrastructure.Domain.Entities.Raca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NomeRaca")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Racas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NomeRaca = "Branca"
                        },
                        new
                        {
                            Id = 2,
                            NomeRaca = "Preta"
                        },
                        new
                        {
                            Id = 3,
                            NomeRaca = "Parda"
                        },
                        new
                        {
                            Id = 4,
                            NomeRaca = "Amarela"
                        },
                        new
                        {
                            Id = 5,
                            NomeRaca = "Indígena"
                        },
                        new
                        {
                            Id = 6,
                            NomeRaca = "Prefere não dizer"
                        });
                });

            modelBuilder.Entity("ProjetoAcoesSustentaveis.Infrastructure.Domain.Entities.StatusUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("StatusUsuario", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Status = "Ativo"
                        },
                        new
                        {
                            Id = 2,
                            Status = "Bloqueado"
                        },
                        new
                        {
                            Id = 3,
                            Status = "Inativo"
                        });
                });

            modelBuilder.Entity("ProjetoAcoesSustentaveis.Infrastructure.Domain.Entities.Telefone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NumeroTelefone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoTelefoneId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TipoTelefoneId");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Telefones");
                });

            modelBuilder.Entity("ProjetoAcoesSustentaveis.Infrastructure.Domain.Entities.TipoTelefone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TipoDeTelefone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TiposTelefone", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TipoDeTelefone = "Telefone Fixo"
                        },
                        new
                        {
                            Id = 2,
                            TipoDeTelefone = "Celular"
                        });
                });

            modelBuilder.Entity("ProjetoAcoesSustentaveis.Infrastructure.Domain.Entities.TipoUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TipoDeUsuario")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TiposUsuario");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TipoDeUsuario = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            TipoDeUsuario = "Gerência"
                        },
                        new
                        {
                            Id = 3,
                            TipoDeUsuario = "Usuario Comum"
                        });
                });

            modelBuilder.Entity("ProjetoAcoesSustentaveis.Infrastructure.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CargoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GeneroId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PossuiDeficiencia")
                        .HasColumnType("bit");

                    b.Property<int>("RacaId")
                        .HasColumnType("int");

                    b.Property<string>("Senha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sobrenome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusUsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("TipoUsuarioId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UltimaAtualizacao")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CargoId");

                    b.HasIndex("DepartamentoId");

                    b.HasIndex("GeneroId");

                    b.HasIndex("RacaId");

                    b.HasIndex("StatusUsuarioId");

                    b.HasIndex("TipoUsuarioId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ProjetoAcoesSustentaveis.Infrastructure.Domain.Entities.Endereco", b =>
                {
                    b.HasOne("ProjetoAcoesSustentaveis.Infrastructure.Domain.Entities.Usuario", "Usuario")
                        .WithOne("Endereco")
                        .HasForeignKey("ProjetoAcoesSustentaveis.Infrastructure.Domain.Entities.Endereco", "UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ProjetoAcoesSustentaveis.Infrastructure.Domain.Entities.Telefone", b =>
                {
                    b.HasOne("ProjetoAcoesSustentaveis.Infrastructure.Domain.Entities.TipoTelefone", "TipoTelefone")
                        .WithMany("Telefones")
                        .HasForeignKey("TipoTelefoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjetoAcoesSustentaveis.Infrastructure.Domain.Entities.Usuario", "Usuario")
                        .WithOne("Telefone")
                        .HasForeignKey("ProjetoAcoesSustentaveis.Infrastructure.Domain.Entities.Telefone", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoTelefone");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ProjetoAcoesSustentaveis.Infrastructure.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("ProjetoAcoesSustentaveis.Infrastructure.Domain.Entities.Cargo", "Cargo")
                        .WithMany("Usuarios")
                        .HasForeignKey("CargoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjetoAcoesSustentaveis.Infrastructure.Domain.Entities.Departamento", "Departamento")
                        .WithMany("Usuarios")
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjetoAcoesSustentaveis.Infrastructure.Domain.Entities.Genero", "Genero")
                        .WithMany("Usuarios")
                        .HasForeignKey("GeneroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjetoAcoesSustentaveis.Infrastructure.Domain.Entities.Raca", "Raca")
                        .WithMany("Usuarios")
                        .HasForeignKey("RacaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjetoAcoesSustentaveis.Infrastructure.Domain.Entities.StatusUsuario", "StatusUsuario")
                        .WithMany("Usuarios")
                        .HasForeignKey("StatusUsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjetoAcoesSustentaveis.Infrastructure.Domain.Entities.TipoUsuario", "TipoUsuario")
                        .WithMany("Usuarios")
                        .HasForeignKey("TipoUsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cargo");

                    b.Navigation("Departamento");

                    b.Navigation("Genero");

                    b.Navigation("Raca");

                    b.Navigation("StatusUsuario");

                    b.Navigation("TipoUsuario");
                });

            modelBuilder.Entity("ProjetoAcoesSustentaveis.Infrastructure.Domain.Entities.Cargo", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("ProjetoAcoesSustentaveis.Infrastructure.Domain.Entities.Departamento", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("ProjetoAcoesSustentaveis.Infrastructure.Domain.Entities.Genero", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("ProjetoAcoesSustentaveis.Infrastructure.Domain.Entities.Raca", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("ProjetoAcoesSustentaveis.Infrastructure.Domain.Entities.StatusUsuario", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("ProjetoAcoesSustentaveis.Infrastructure.Domain.Entities.TipoTelefone", b =>
                {
                    b.Navigation("Telefones");
                });

            modelBuilder.Entity("ProjetoAcoesSustentaveis.Infrastructure.Domain.Entities.TipoUsuario", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("ProjetoAcoesSustentaveis.Infrastructure.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Endereco");

                    b.Navigation("Telefone");
                });
#pragma warning restore 612, 618
        }
    }
}
